api/urls.py
# api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path("appointments/", views.UserAppointmentAPIView.as_view(), name="user-appointments"),
]

config/urls.py
# config/urls.py :
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('pages.urls')),
    path('api/', include('api.urls')),

    # path('api-auth/', include('rest_framework.urls')),
 
]

pages/urls.py
# pages/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm


app_name = "pages"



urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("cooming_soon/", views.CommingSoonPage.as_view(), name="comming_soon"),

    path("register/", views.RegistrationView.as_view(), name="register"),
    path('login/', auth_views.LoginView.as_view(
        template_name='pages/public/user/auth/login.html',
        authentication_form=UserLoginForm,
        redirect_authenticated_user=True # Redirect if user is already logged in
    ), name='login'),


    path("login/", views.LoginPage.as_view(), name="login"),
    path("dashboard/", views.DashboardPage.as_view(), name="dashboard"),
    path("logout/", views.logout_view , name="logout"),

]

templates/partials/navbar.html
<nav class="navbar">
    <div class="container nav-container">
        <div class="logo">
            <a href="#">عود آرامش</a>
        </div>

        {% if user.is_authenticated %}
        {{ user.username }}
        <div class="nav-links">
            <a href="{% url 'pages:logout' %}" class="nav-button login-btn">خروج</a>
            <a href="{% url 'pages:comming_soon' %}" class="nav-button signup-btn">فرشگاه</a>
            <a href="{% url 'pages:dashboard' %}" class="nav-button signup-btn">داشبورد کاربری</a>
        </div>
        {% else %}
        <div class="nav-links">
            <a href="{% url 'pages:login' %}" class="nav-button login-btn">ورود</a>
            <a href="{% url 'pages:register' %}" class="nav-button signup-btn">ثبت نام</a>
        </div>
        {% endif %}

    </div>
</nav>